import { APP_URL } from "./constants";
import { ROLE, Role } from "./roles";

export const roleRoutes: Record<Role, string[]> = {

    [ROLE.SUPER_ADMIN]: [
        APP_URL.DASHBOARD,
        // MANAGE SCHOOL
        APP_URL.MANAGE_SCHOOL,
        APP_URL.CREATE_SCHOOL,
        // SCHOOL IMPORT
        // APP_URL.SCHOOL_IMPORT,

        // // WEBSITE / TEMPLATE

        // APP_URL.WEBSITE_TEMPLATE,
        // APP_URL.TEMPLATE_MANAGER,

        // // ALERTS

        // APP_URL.ALERTS,
        // APP_URL.WHATSAPP_ALERTS,
        // APP_URL.WHATSAPP_ALERTS_TEMPLATE,
        // APP_URL.WHATSAPP_ALERTS_ADD_TEMPLATE,
        // APP_URL.APP_NOTIFICATIONS,
        // APP_URL.MULTI_SCHOOL,
        // APP_URL.REPORT_TABLE,

        // // VALIDATIONS
        // APP_URL.VALIDATIONS,

        // // TECH SUPPORT
        // APP_URL.TECH_SUPPORT,
        // APP_URL.TECH_SUPPORT_TICKETING,
        // APP_URL.TECH_SUPPORT_USER,
        // APP_URL.TECH_SUPPORT_REPORT,

        // // APP CONFIGURATION

        // APP_URL.APP_CONFIGURATION,
        // APP_URL.APP_CONFIGURATION_THEME,
        // APP_URL.APP_CONFIGURATION_THEME_ADD,
        // APP_URL.APP_CONFIGURATION_ASSET_TYPE,
        // APP_URL.APP_CONFIGURATION_ASSET_VALUE,
        // APP_URL.APP_CONFIGURATION_VERSION_MANAGER,
        // APP_URL.APP_CONFIGURATION_MODULE_MANAGER,

        // // PRIVACY POLICY
        // APP_URL.PRIVACY_POLICY,
    ],


    [ROLE.SCHOOL]: [
        APP_URL.DASHBOARD,

        //Manage User
        APP_URL.MANAGE_USER,

        // SCHOOL SETUP (Base)

        // Academic
        APP_URL.SCHOOL_SETUP_ACADEMIC_SESSION,
        APP_URL.SCHOOL_SETUP_ACADEMIC_SESSION_CARRY_FORWARD,

        // Structure
        APP_URL.SCHOOL_SETUP_CLASS_SECTION,
        APP_URL.SCHOOL_SETUP_MANAGE_GROUP,
        APP_URL.SCHOOL_SETUP_MANAGE_SUBJECT,

        // Admin & Admission
        APP_URL.SCHOOL_SETUP_ADMINISTRATOR,
        APP_URL.SCHOOL_SETUP_ADMINISTON,

        // Banking & Category
        APP_URL.SCHOOL_SETUP_BANK_BRANCHES,
        APP_URL.SCHOOL_SETUP_CATEGORY,

        // Configuration
        APP_URL.SCHOOL_SETUP_CONFIGURATION,
        APP_URL.SCHOOL_SETUP_WHATSAPP_CONFIGURATION,
        APP_URL.SCHOOL_SETUP_OTHER_SETTINGS,

        // Dashboard / Notes
        APP_URL.SCHOOL_SETUP_DASHBOARD_RUNNING_NOTE,

        // Calendar & Leave
        APP_URL.SCHOOL_SETUP_HOLIDAY_CALENDAR,
        APP_URL.SCHOOL_SETUP_LEAVE_REMARKS,

        // HR / Staff
        APP_URL.SCHOOL_SETUP_MANAGE_DEPARTMENT,
        APP_URL.SCHOOL_SETUP_MANAGE_DESIGNATION,
        APP_URL.SCHOOL_SETUP_TEACHERS,

        // Hostel / Houses
        APP_URL.SCHOOL_SETUP_MANAGE_HOSTEL,
        APP_URL.SCHOOL_SETUP_MANAGE_HOUSES,

        // Transport & Vendor
        APP_URL.SCHOOL_SETUP_TRANSPORTATION,
        APP_URL.SCHOOL_SETUP_VENDOR_MANAGEMENT,

        // CMS (Base)
        APP_URL.CMS,
        APP_URL.CMS_WEB,
        APP_URL.CMS_WEB_MANAGER,
        APP_URL.CMS_ACADEMIC_CMS,
        APP_URL.CMS_TEMPLATE_MANAGER,

    //     // Student Attendance

        APP_URL.STUDENT_ATTENDANCE,
        APP_URL.STUDENT_ATTENDANCE_ASSIGN_HOLIDAY,
        APP_URL.STUDENT_ATTENDANCE_ATTENDANCE,
        APP_URL.STUDENT_ATTENDANCE_LEAVES,
        APP_URL.STUDENT_ATTENDANCE_REPORT,
        APP_URL.STUDENT_ATTENDANCE_SETTINGS,

    //     // Manage Fee
    //     APP_URL.MANAGE_FEE,
    //     APP_URL.CHEQUE_BOUNCE,
    //     APP_URL.FEE_GROUP_STRUCTURE,
    //     APP_URL.ADD_FEE_GROUP_STRUCTURE,
    //     APP_URL.MANAGE_FINE,
    //     APP_URL.STUDENT_FEE_STRUCTURE,
    //     APP_URL.ADD_STUDENT_FEE_STRUCTURE,

    //     //Message 
    //     APP_URL.GROUP_SMS,
    //     APP_URL.MESSAGE_LOG,
    //     APP_URL.SEND_MESSAGE_WHATSAPP,
    //     APP_URL.MESSAGE_TEMPLATES,

        //Admission
        APP_URL.ADMISSION_ACTIVITY,
        APP_URL.ADMISSION_FIELD_WISE_MODIFY,
        APP_URL.ADMISSION_REPORTS,
        APP_URL.ADMISSION_ROLLNO_ALLOTMENT,
        APP_URL.ADMISSION_SHUFFLE_CLASSES,
        APP_URL.ADMISSION_SLC_CERTIFICATES,
        APP_URL.ADMISSION_STRUCKOFF_WITHDRAWAL,
        APP_URL.ADMISSION_STUDENT_DOC_IMPORT,
        APP_URL.ADMISSION_STUDENT_INFO_ADD,
        APP_URL.ADMISSION_STUDENT_INFO_LIST,
        APP_URL.ADMISSION_STUDENT_OFFICIAL_MULTI,
        APP_URL.ADMISSION_STUDENT_SUBJECT_MAP,

        //Manage Fee
        APP_URL.MANAGE_FEE_FEE_GROUP_STRUCTURING,
        APP_URL.MANAGE_FEE_FEE_CONCESSION,
    ],



    // [ROLE.STAFF]: [
    //     APP_URL.DASHBOARD
    // ],

    // [ROLE.PARENT]: [
    //     APP_URL.DASHBOARD
    // ],
}